// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYUSZIwuSvnMFwQFBRfFBB-UOgDu81FL0',
    appId: '1:79167796225:android:771c628eab686ed4aafc00',
    messagingSenderId: '79167796225',
    projectId: 'test-afaf1',
    storageBucket: 'test-afaf1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQeTFhAQwlaJv4R0_8jwkUeQlTmIAdrNw',
    appId: '1:79167796225:ios:8ac52484d5b68deeaafc00',
    messagingSenderId: '79167796225',
    projectId: 'test-afaf1',
    storageBucket: 'test-afaf1.firebasestorage.app',
    iosBundleId: 'com.phieunhap.devtest.phieuNhap',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBEua2OXIVB3-0xpiGt4siONOf2G7Sd6qU',
    appId: '1:79167796225:web:80d1b04196084b41aafc00',
    messagingSenderId: '79167796225',
    projectId: 'test-afaf1',
    authDomain: 'test-afaf1.firebaseapp.com',
    storageBucket: 'test-afaf1.firebasestorage.app',
  );
}
